server:
  port: 8080
  context-path: /api/v1
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trivor-insights
cloud:
  aws:
    queues:
      trivorInsights: trivor-insights-dev
    buckets:
      trivorSubtitles: trivor-storage-dev
    region:
      static: us-east-1
    credentials:
      instanceProfile: false
