spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trivor-insights
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
