server:
  port: 8080
spring:
  application:
    name: trivor-engine
  data:
    mongodb:
      host: localhost
      port: 27017
cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      instanceProfile: false
