server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
cloud:
  aws:
    queues:
      trivorInsights: trivor-insights-dev
    buckets:
      trivorSubtitles: trivor-storage-dev
    region:
      static: us-east-1
    credentials:
      instanceProfile: false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
