server:
  port: 8080
app:
  env: dev
spring:
  application:
    name: trivor-engine
  data:
    mongodb:
      host: localhost
      port: 27017
cloud:
  aws:
    queues:
      trivorInsights: trivor-insights-${app.env}
    buckets:
      trivorSubtitles: trivor-storage-${app.env}
    region:
      static: us-east-1
    credentials:
      instanceProfile: false

