#!/bin/bash

SERVICE=$1

if [ "$SERVICE" == "insights" ] || [ -z "$SERVICE" ]; then
    echo "Building insights"
    cd insights && ./mvnw clean package -DskipTests=true
    wait
fi

echo "Running docker-compose"
docker-compose stop $SERVICE
docker-compose build $SERVICE
docker-compose up $SERVICE