#!/bin/bash

SERVICE=$1

if [ "$SERVICE" == "trivor-engine" ] || [ -z "$SERVICE" ]; then
    echo "Building trivor-engine"
    cd trivor-engine && ./gradlew clean build
fi

echo "Running docker-compose"
docker-compose stop $SERVICE
docker-compose up $SERVICE